"use client"
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from "react";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from "@emotion/react";
import theme from './../Theme';
import Navbar from "@/_Components/Navbar/Navbar";
import { Box } from "@mui/material";
import { ToastContainer } from "react-toastify";
import { Provider } from "react-redux";
import { store } from './../Redux/store';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children} : {children :ReactNode}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {/* navbar is client component */}
        <Box sx={{pt:10}}>
        <Navbar/> 
        {children}
        <ToastContainer />

        </Box>
        </ThemeProvider>
        </AppRouterCacheProvider>
        </Provider>
      </body>
    </html>
  );
}
